#! /bin/bash

set -euo pipefail

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $DIR/awsm-cli/_common_logging.sh

while true; do
  case "${1:-}" in
    -h | --help)
      echo "$(cat "$DIR/awsm-cli/USAGE")" >&2
      exit 1
      ;;
    --?)
      echo "Invalid Option: --$1" 1>&2
      exit 1
      ;;
    -?)
      echo "Invalid Option: -$1" 1>&2
      exit 1
      ;;
    -*)
      split=$1
      shift
      set -- $(echo "$split" | cut -c 2- | sed 's/./-& /g') "$@"
      continue
      ;;
    *)
      break
      ;;
  esac
done

die() {
  printf "$1\n" >&2
  exit 1
}

command="${1:-}"
subcommand="${2:-}"
if [ "$command" == "pretty" ]; then
  exec column -t -s $'\t' -n
elif [ "$command" == "internal" ]; then
  [ ! -t 0 ]                               || die "$(ansi.red "ERROR"): You must pipe some data into this internal subcommand \`$subcommand\`."
  [ -f "$DIR/awsm-cli/${subcommand}.awk" ] || die "$(ansi.red "ERROR"): Internal subcommand \`$subcommand.awk\` not found."

  shift 2
  exec "$DIR/awsm-cli/${subcommand}.awk" "$@"
else
  [ ! -z "$command" ] && [ ! -z "$subcommand" ]      || die "$(ansi.red "ERROR"): Both \`command\` and \`subcommand\` are required. See usage.\n\n$(cat "$DIR/awsm-cli/USAGE")"
  [ -f "$DIR/awsm-cli/${command}-${subcommand}.sh" ] || die "$(ansi.red "ERROR"): AWSM does not yet support command \`$command\` and subcommand \`$subcommand\`."

  shift 2
  exec "$DIR/awsm-cli/${command}-${subcommand}.sh" "$@"
fi
